"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { useEffect, useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "@/firebase";
import { usePathname, useRouter } from "next/navigation";
import { ToastContainer, toast } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const pathname = usePathname();
  const [user, setUser] = useState(null);

  const hideNavAndFooter =
    pathname === "/login" || pathname === "/signup" || pathname === "/profiles";

  useEffect(() => {
    // Ensure we're on the client side before accessing localStorage
    if (typeof window !== "undefined") {
      const storedUser = localStorage.getItem("user");
      console.log("Stored user:", storedUser);
      if (storedUser && storedUser !== "null" && storedUser !== "undefined") {
        try {
          setUser(JSON.parse(storedUser));
        } catch (error) {
          console.error("Error parsing stored user:", error);
          // Clear invalid data from localStorage
          localStorage.removeItem("user");
          setUser(null);
          router.push("/login");
        }
      } else {
        setUser(null);
        router.push("/login");
      }
    }
  }, []);

  useEffect(() => {
    onAuthStateChanged(auth, async (user) => {
      if (user) {
        console.log("User is signed in:", user);
      } else {
        console.log("No user is signed in.");
        if (window.location.pathname !== "/login") {
          router.push("/login");
        }
        setUser(null);
      }
    });
  }, [user]);

  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/netflix_favicon.ico" />
        <title>WatchHub - Watch All Trending Movies</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {!hideNavAndFooter && user && <Navbar />}
        <ToastContainer theme="dark" />
        {children}
        {!hideNavAndFooter && user && <Footer />}
      </body>
    </html>
  );
}
